# command line
default: -p pretty -p html -p json -p chrome -p producao 
ci: -p progress -p html -p json -p chrome_headless -p producao --retry 1

# report type
html: --format html --out=logs/report.html
json: --format json --out=logs/report.json

# log style
pretty: --format pretty
progress: --format progress

# browsers
firefox: BROWSER=firefox
chrome: BROWSER=chrome
chrome_headless: BROWSER=chrome-headless

homolog: TEST_ENV=HML
producao: TEST_ENV=PROD

HML:
  :url: http://bradesco-painel-hml.s3-website-sa-east-1.amazonaws.com/login/
  :medico_01: 62242970704
  :medico_02: 21814872353
  :medico_elegibilidade: 10176389776
  :sec_01: 71827072849
  :password: Teste123
  :carteirinha_valida: 771667009741026
  :carteirinha_invalida: 951080476260860000
  
PROD: 
  :url: https://saudedigital.bradescosaude.com.br/login/
  :medico_01: 95520457034
  :medico_02: 49773827810
  :medico_elegibilidade: 10176389776
  :sec_02: 88185630178
  :sec_01: 61336921463
  :password: Teste123
  :carteirinha_valida: 771667009741026
  :carteirinha_invalida: 951080476260860000


  